name: Firmware release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini')}}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Checkout custom devices
        uses: actions/checkout@v3
        with:
          repository: MobiFlight/MobiFlight-CustomDevices
          ref: '0.2.0'
          path: CustomDevices

      - name: Extract build version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Get Core version
        run: |
          git remote add other_repo https://github.com/MobiFlight/MobiFlight-FirmwareSource
          git fetch other_repo --tags
          git describe --tags --abbrev=0 other_repo/main
          echo "CORE_VERSION=$(git describe --tags --abbrev=0 other_repo/main)" >> $GITHUB_ENV

      - name: Run PlatformIO
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
          CORE_VERSION: ${{ env.CORE_VERSION }}
        run: |
          echo $VERSION
          echo $CORE_VERSION
          pio run

      - name: Add FW files to Community Folder and zip
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
        run: |
          chmod +x ./copy_fw_files.sh
          ./copy_fw_files.sh
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            CustomDevices_own/**/**/*.zip
