name: Firmware release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini')}}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Checkout custom devices
        uses: actions/checkout@v3
        with:
          repository: MobiFlight/MobiFlight-CustomDevices
          ref: '0.2.0'
          path: CustomDevices

      - name: Extract build version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Run PlatformIO
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
        run: pio run

      - name: Add FW files to Community Folder and zip
        run: |
          mkdir CustomDevices_own/Gagagu/Community/firmware
          cp -r .pio/build/gagagu_fcu_efis_mega/*.hex CustomDevices_own/Gagagu/Community/firmware
          cp -r .pio/build/gagagu_fcu_efis_raspberrypico/*.uf2 CustomDevices_own/Gagagu/Community/firmware
          cd CustomDevices_own/Gagagu/Community
          zip -r -qq Community_${{ github.event.release.tag_name }}.zip *

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            CustomDevices_own/**/**/*.zip
